name: CI/CD Build and Test for MC426
run-name: ${{ github.actor }} is creating this pipeline for the MC426 project

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Building the aplication 
        run: |
          cd backend/docker/
          ./build.sh
      - name: Running the aplication inside of a container, with the image created in build.
        run: |
          cd backend/docker/
          ./run.sh
          echo "Doing the healthy check test."
          docker stop run
      - run: echo "This job's status is ${{ job.status }}."
  
  build-ios-dummy:
    runs-on: macos-latest
    needs: []
    steps:
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.2"
          channel: 'stable'
      - name: Building
        run: |
          cd front/
          flutter upgrade
          flutter pub get
          flutter clean
          echo "THE BUILD IOS WONT WORK, BECAUSE WE DONT HAVE AN VALID CODE SIGNING CERTIFICATE. IS NEEDED AN APPLE DEVELOPER ACCOUNT, APPLE ID, ETC..."
      - run: echo "This job's status is ${{ job.status }}."
  
  build-android:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.2"
          channel: 'stable'
      - name: Building
        run: |
          cd front/
          flutter upgrade
          flutter pub get
          flutter clean
          flutter build appbundle
      - name: Upload appbundle
        uses: actions/upload-artifact@v2.1.4
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
      - run: echo "This job's status is ${{ job.status }}."

  test-backend:
    runs-on: ubuntu-latest
    needs: [build-backend]
    steps:
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend/app
          pip install -r requirements.txt
      - name: Testing the aplication of sign in and sign up functionalitiy
        run: |
          cd backend
          python3 -m app.login.tests
      - name: Testing the aplication of posts functionalitiy
        run: |
          cd backend
          python3 -m app.posts.tests
      - name: Testing the aplication of map functionalitiy
        run: |
          cd backend
          python3 -m app.map.tests
      - name: Testing the aplication of profile functionalitiy
        run: |
          cd backend
          python3 -m app.profile.tests
      - run: echo "This job's status is ${{ job.status }}."
  
  test-front:
    runs-on: ubuntu-latest
    needs: [build-ios-dummy, build-android]
    steps:
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.2"
          channel: 'stable'
      - name: Install dependencies
        run: |
          cd front/
          flutter upgrade
          flutter pub upgrade get_it
          flutter pub add dev:test
      - name: Testing the aplication of sign in and sign up functionalitiy
        run: |
          cd front/
          flutter analyze
          flutter test test/src/tests.dart
      - run: echo "This job's status is ${{ job.status }}."
